#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@3.19.24.179:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:

      #jpa ddl-auto
      ddl-auto: create

    show-sql: true

    #jpa format
    properties:
      hibernate:
        format_sql: true

  #log
  output:
    ansi:
      enabled: always

